### ISSUE TITLE
BIP-239 Discussion?

### ISSUE THREAD

**Issue by Danconnolly** [bitcoin-sv/arc#14]
[BIP-239](https://github.com/bitcoin-sv/arc/blob/master/doc/BIP-239.md) appears to be proposal for a standard.

Is this proposal being formally raised? Is there a discussion taking place?

**Comment by sirdeggen** [comment]
I'm not sure whether there has been much discussion out with the conversations I've had with the authors and a few others during ad hoc meetings.

I asked it to be included in the BRCs repo [here](https://github.com/bitcoin-sv/BRCs/blob/master/transactions/0030.md) in attempt to capture it as a proposed standard to be discussed. Any suggestions for improvement or discussion around the proposal ought to be conducted within the issues section of that repository. Perhaps other forums are preferred but that link would be ideal.

**Comment by Danconnolly** [comment]
ok thanks Deggen, I'll take a look over there.
