### ISSUE TITLE
Broadcast timeout

### ISSUE THREAD

**Issue by zpxp** [bitcoin-sv/arc#319]
Hello

What http status and TxStatus does the broadcast endpoint return if `X-MaxTimeout` is reached? Tried testing it by setting it to 1 or 0 but it doesnt seem to affect the duration. Basically what is the api going to return if it times out?

**Comment by boecklim** [comment]
Hello @zpxp 
Sorry for the late reply.

If the timeout is reached, the http status expected is 200 and the tx status expected would be the status which that transaction has a the moment of timeout. 

I just verified the `X-MaxTimeout` header with value 1s by sending a tx to TAAL's `mainnet` ARC `https://arc.taal.com/v1/tx` with header `X-WaitForStatus: 9` (status MINED => response will timeout). 

As expected the response was received after ~1s.

**Comment by zpxp** [comment]
Thanks
