### ISSUE TITLE
Client Feedback & Simple Bug Report

### ISSUE THREAD

**Issue by kurtwuckertjr** [bitcoin-sv/arc#4]
Here's a mix of feedback we've received after a few days of a few apps testing: 

First impressions:

 - seems to perform better than mAPI, but worse than p2p
 - looks like a well thought out architecture
 - didn't immediately got the client package working so created the http requests myself
 - bug: received txStatus REJECTED while a tx went through anyway

**Comment by sirdeggen** [comment]
Good feedback thanks for sharing it here.

> "but worse than p2p" 

Does this mean that using a `sendrawtransaction` method over json-rpc against your own node is a better experience?
