### ISSUE TITLE
BlockTx Stores all Txids rather than just the ones it has been sent directly

### ISSUE THREAD

**Issue by sirdeggen** [bitcoin-sv/arc#49]
The service is supposed to store all txids from a block so that when a submission comes in with a tx which has already been mined the correct status can be reported. However, there is no requirement in general for txids to be stored beyond those which the service has received from counterparties. This is a workaround for ensuring ARC's retry logic doesn't keep these submissions in an infinite retry loop just because the other nodes are ignoring the attmpted broadcast.

**Comment by sirdeggen** [comment]
Known issues include the fact that not all txids are actually stored when it comes to large blocks.

**Comment by boecklim** [comment]
Hello @sirdeggen 
This issue would be addressed by this open PR: https://github.com/bitcoin-sv/arc/pull/254

The feature of ARC to report MINED status which have been submitted not through that ARC instance will be lost for now, but is planned to be added again at a later stage with a new service.

**Comment by boecklim** [comment]
This issue has been addressed. Closing it.
